.github/workflows/test.yml
ci/scripts/build_example.sh
ci/scripts/build_iceberg.sh
example/CMakeLists.txt

This PR adds a minimal build for Ubuntu 24.04, macOS 14 and Windows 2019 for both Iceberg CPP and the Example to validate follow up PRs build correctly.

Add basic CI to build iceberg and example

---

.github/workflows/cpp-linter.yml
api/iceberg/table.h

Add GitHub cpp-linter-action

---

NOTICE

Iceberg C++ was started at year 2024, so change to it.

fix wrong copyright year range

---

docs/Doxyfile
docs/README.md
src/iceberg/table.h

I opted not to configure a theme but we could vendor something like [Doxygen Awesome](https://jothepro.github.io/doxygen-awesome-css/) (this is MIT).
Fixes #26.

Add Doxygen for generating API documentation

---

.asf.yaml

Add some active contributors who are not yet Iceberg committers as collaborators to facilitate contribution.

ci: add initial collaborators

---

docs/Doxyfile
src/iceberg/CMakeLists.txt
src/iceberg/schema.cc
src/iceberg/schema.h
src/iceberg/schema_field.cc
src/iceberg/schema_field.h
src/iceberg/type.cc
src/iceberg/type.h
src/iceberg/type_fwd.h
src/iceberg/util/formattable.h
src/iceberg/util/formatter.h
test/core/CMakeLists.txt
test/core/schema_field_test.cc
test/core/schema_test.cc
test/core/type_test.cc

Implement the API for data types and schemas.

Add data type/schema field/schema

---

src/iceberg/exception.h
src/iceberg/schema_field.cc
src/iceberg/type.cc
src/iceberg/type.h
test/core/schema_field_test.cc
test/core/type_test.cc

- Fix some clang-tidy lints (`virtual ~Foo() = default` -> `~Foo() override = default`, missing `explicit`)
- Add `iceberg::IcebergError` instead of `std::runtime_error`
- Make field repr explicitly put `(optional)`
- Note current time complexity of field accessors

Make field repr explicit about optionality, add exception type

---

src/iceberg/CMakeLists.txt
src/iceberg/error.h
src/iceberg/exception.h
src/iceberg/partition_field.cc
src/iceberg/partition_field.h
src/iceberg/partition_spec.cc
src/iceberg/partition_spec.h
src/iceberg/transform.cc
src/iceberg/transform.h
src/iceberg/type_fwd.h
test/CMakeLists.txt
test/partition_field_test.cc
test/partition_spec_test.cc
test/transform_test.cc

- Implement the API for partition spec/field.
- add pure virtual classes for transform

feat: add partition field/partition spec

---

src/iceberg/arrow/arrow_error_transform_internal.h
src/iceberg/json_internal.cc
src/iceberg/json_internal.h
src/iceberg/partition_field.cc
src/iceberg/partition_field.h
src/iceberg/partition_spec.cc
src/iceberg/schema_field.cc
src/iceberg/schema_internal.cc
src/iceberg/schema_internal.h
src/iceberg/sort_field.cc
src/iceberg/sort_field.h
src/iceberg/sort_order.cc
src/iceberg/transform.h
src/iceberg/type.cc
test/json_internal_test.cc
test/partition_field_test.cc
test/partition_spec_test.cc
test/schema_field_test.cc
test/schema_test.cc
test/sort_field_test.cc
test/sort_order_test.cc
test/transform_test.cc
test/type_test.cc

It is suggested that we include result.h instead of expected.h so that in the future we can simply replace this ported iceberg::expected with std::expected.
Besides that, I fix some IWYU warning in this PR.

chore: don't include expected.h but result.h

---

.github/.licenserc.yaml
LICENSE
NOTICE
src/iceberg/CMakeLists.txt
src/iceberg/util/murmurhash3_internal.cc
src/iceberg/util/murmurhash3_internal.h

Which will be used by BucketTransform.

feat: adopt MurmurHash3

---

src/iceberg/statistics_file.cc
src/iceberg/util/formatter.h
src/iceberg/util/formatter_internal.h
test/CMakeLists.txt
test/formatter_test.cc

- Added std::formatter specialization for std::map, std::unordered_map and std::vector when their elements are also formattable.
- Added std::formatter specialization for classes that have a ToString at hands.

feat: add formatter specialization

---

cmake_modules/IcebergThirdpartyToolchain.cmake

FetchContent_MakeAvailable generate a <lowercaseName>_SOURCE_DIR[1], for arrow it's arrow_SOURCE_DIR. arrow use a internal arrow_SOURCE_DIR to set its THIRDPARTY_DIR[2].
The generated arrow_SOURCE_DIR overwrite the arrow's interal arrow_SOURCE_DIR, causing the following build error:
CMake Error at build/_deps/arrow-src/cpp/cmake_modules/ThirdpartyToolchain.cmake:449 (file):
file STRINGS file
"/Users/zhjwpku/zhjwpku/iceberg-cpp/build/_deps/arrow-src/thirdparty/versions.txt"
cannot be read.
Fix this issue by renaming fetchcontent_declare name from Arrow to VendoredArrow.
[1] https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_makeavailable
[2] https://github.com/apache/arrow/blob/main/cpp/cmake_modules/ThirdpartyToolchain.cmake#L368

chore: fix a build error due to name conflict

---

src/iceberg/util/config.h
test/CMakeLists.txt
test/config_test.cc

introduce a new config class to manage configurable options following design ideas from Velox

feat: add base config implementation

---

src/iceberg/json_internal.cc

1. switch off exceptions for nlohmann::json::parse
2. add a no except wrapper around json.dump, since we don't handle exceptions in Error messages.
This closes issue #87
References:
- https://json.nlohmann.me/features/parsing/parse_exceptions/
- https://json.nlohmann.me/api/basic_json/dump/

chore: better error handling of nlohmann json lib apis

---

src/iceberg/json_internal.cc
src/iceberg/json_internal.h
src/iceberg/name_mapping.cc
src/iceberg/name_mapping.h
src/iceberg/type_fwd.h
test/json_internal_test.cc
test/name_mapping_test.cc

- add roundtrip json conversion to name mapping
- change MappedField to use std::shared_ptr for better usability
- use optional field_id in MappedField

feat: add json serde to name mapping

---

src/iceberg/CMakeLists.txt
src/iceberg/file_format.h
src/iceberg/manifest_entry.cc
src/iceberg/manifest_entry.h
src/iceberg/manifest_list.cc
src/iceberg/manifest_list.h
src/iceberg/manifest_reader.h
src/iceberg/schema_field.h
src/iceberg/type_fwd.h

Add DataFile, ManifestEntry, ManifestFile, and ManifestList to Iceberg core.
Support for parsing these data structures from Avro file will be added in future PRs.

feat: add manifest related structures

---

src/iceberg/CMakeLists.txt
src/iceberg/schema_util.cc
src/iceberg/schema_util.h
test/CMakeLists.txt
test/schema_util_test.cc

Implement a `SchemaProjection` companion data structure to work with expected `Schema` to carry projection result. This is useful to project data returned by different file format reader implementations.

feat: add schema projection support

---

src/iceberg/CMakeLists.txt
src/iceberg/result.h
src/iceberg/table_metadata.cc
src/iceberg/util/gzip_internal.cc
src/iceberg/util/gzip_internal.h
test/CMakeLists.txt
test/gzip_decompress_test.cc
test/metadata_io_test.cc

support gzip compressed metadata json

feat: support decompress gzip metadata

---

src/iceberg/CMakeLists.txt
src/iceberg/arrow/arrow_fs_file_io.h
src/iceberg/avro/avro_data_util.cc
src/iceberg/avro/avro_data_util_internal.h
src/iceberg/avro/avro_reader.cc
src/iceberg/avro/avro_reader.h
src/iceberg/avro/demo_avro.cc
src/iceberg/expected.h
src/iceberg/file_reader.cc
src/iceberg/file_reader.h
src/iceberg/result.h
src/iceberg/schema_internal.h
test/avro_test.cc

- Refactor a little bit of Reader and ReaderFactory interfaces.
- Implement the skeleton of Avro reader to read data into ArrowArray.
- `AppendDatumToBuilder` is not implemented yet.

feat: implement avro file reader

---

src/iceberg/json_internal.cc
src/iceberg/schema_util.cc
src/iceberg/transform.cc

fix some compilation warnings. see issue (https://github.com/apache/iceberg-cpp/issues/118)

fix: fix build warning in switch case (#118)

---

src/iceberg/partition_field.h
src/iceberg/partition_spec.h
src/iceberg/schema.h
src/iceberg/schema_field.h
src/iceberg/snapshot.h
src/iceberg/sort_field.h
src/iceberg/sort_order.h
src/iceberg/statistics_file.h
src/iceberg/table_metadata.h
src/iceberg/transform.h
src/iceberg/type.cc
src/iceberg/type.h

C++20 supports rewrite candidates, see https://en.cppreference.com/w/cpp/language/overload_resolution.html#Call_to_an_overloaded_operator
> For `x != y`, all member, non-member, and built-in `operator==`s found are added to the set, unless there is a matching `operator!=`.

refactor: remove explicit operator!= using C++20 rewrite candidates

---

src/iceberg/expression/expression.cc
src/iceberg/expression/expression.h
test/expression_test.cc

- or expression
- change negate return type form Result to Expression
- add some tests

feat: add or expression

---

cmake_modules/IcebergThirdpartyToolchain.cmake
src/iceberg/CMakeLists.txt

Added `spdlog` as a third-party dependency to implement logger support. My plan is to add a logger interface so we don't expose `spdlog` symbols externally (just like what we did with `nanoarrow` and `nlohman-json`).

feat: add spdlog dependency to implement logging

---

src/iceberg/arrow/arrow_fs_file_io.cc
src/iceberg/arrow/arrow_fs_file_io_internal.h
src/iceberg/avro/avro_reader.cc
test/arrow_fs_file_io_test.cc
test/avro_test.cc
test/gzip_decompress_test.cc
test/manifest_list_reader_test.cc
test/metadata_io_test.cc

Rename `arrow_fs_file_io.h` to `arrow_fs_file_io_internal.h` to avoid accidentally installing it.

feat: add in-memory FileIO backed by Arrow MockFileSystem

---

test/in_memory_catalog_test.cc
test/manifest_reader_test.cc

PR #148 renames arrow_fs_file_io.h to arrow_fs_file_io_internal.h, Since CI does not re-run after a PR is merged, conflicts arose with other PR changes, thus the CI failure on main branch.

fix: wrong header inclusion

---

src/iceberg/table_scan.cc

extract partition schema from table meta and pass it to manifest reader

feat: pass partition schema to manifest reader

---

src/iceberg/file_writer.h
src/iceberg/manifest_writer.h

[Define of file writer and manifest writer](feat: add file writer and manifest writer interface definition)

feat: add file writer and manifest writer interface definition

---

src/iceberg/manifest_entry.h

kContent in manifest entry should be optional, not required

fix: content in manifest entry should be optional

---

src/iceberg/type_fwd.h

Enhanced the forward declaration system in `type_fwd.h` to reduce compilation dependencies and improve build times.
- Added missing forward declarations for commonly used classes  
- Reorganized declarations into logical groups with descriptive comments  
- Removed outdated TODO comment regarding  (These classes were already properly declared):  
- `StructLike`  
- `MetadataUpdate`  
- `UpdateRequirement`  
- `AppendFiles`

refactor: enhance forward declarations in type_fwd.h to reduce compile dependencies

---

.gitignore
src/iceberg/CMakeLists.txt
src/iceberg/arrow/arrow_error_transform_internal.h
src/iceberg/constants.h
src/iceberg/parquet/parquet_reader.cc
src/iceberg/parquet/parquet_register.cc
src/iceberg/parquet/parquet_schema_util.cc
src/iceberg/parquet/parquet_writer.cc
src/iceberg/parquet/parquet_writer.h
src/iceberg/schema_internal.cc
src/iceberg/schema_internal.h
src/iceberg/type.cc
src/iceberg/type.h
test/arrow_test.cc
test/parquet_test.cc

Add parquet writer factory and basic parquet writer without metrics.

feat: implement basic parquet writer and add roundtrip tests

---

src/iceberg/table_scan.cc
src/iceberg/table_scan.h
test/CMakeLists.txt
test/file_scan_task_test.cc

Introduces a new method `FileScanTask::ToArrow()` which returns a standard struct `ArrowArrayStream`. This makes iceberg-cpp a first-class citizen in the Arrow ecosystem.
+ `FileScanTask::ToArrow()` is added. It takes the projected schema, filter, and FileIO as arguments to create and configure a file-format-specific reader (ParquetReader, etc.).
+ A new factory function, `MakeArrowArrayStream`, is introduced. It takes an internal C++ Reader instance and wraps it in an `ArrowArrayStream`, correctly managing state and resource lifecycle via the C interface callbacks (`get_schema`, `get_next`, `release`).

feat: read data from FileScanTask as Arrow C Stream

---

.github/workflows/test.yml
cmake_modules/IcebergThirdpartyToolchain.cmake
src/iceberg/CMakeLists.txt
src/iceberg/IcebergConfig.cmake.in
test/CMakeLists.txt
test/roaring_test.cc

- Integrated CRoaring library into the project by adding a new function to resolve its dependency in `IcebergThirdpartyToolchain.cmake`.
- Updated the CMakeLists to include CRoaring in both static and shared build interfaces.

feat: add CRoaring dependency

---

src/iceberg/avro/avro_stream_internal.cc
src/iceberg/type.cc
src/iceberg/util/decimal.cc

This will simplify the code and potentially optimize the binary due to the [[unlikely]] attribute in ICEBERG_CHECK.

refactor: use ICEBERG_CHECK where possible

---

.github/workflows/cpp-linter.yml
.github/workflows/sanitizer_test.yml
.github/workflows/test.yml
CMakeLists.txt
cmake_modules/IcebergThirdpartyToolchain.cmake
example/CMakeLists.txt
src/iceberg/CMakeLists.txt
src/iceberg/IcebergConfig.cmake.in
src/iceberg/catalog/CMakeLists.txt
src/iceberg/catalog/rest/CMakeLists.txt
src/iceberg/catalog/rest/rest_catalog.cc
src/iceberg/catalog/rest/rest_catalog.h

Add cpr and curl dependency for REST catalog. This is related to #232 .
The current code in the REST package is just a demo example to verify the feasibility of cpr, which will be replaced in future commits. The actual content will be added in subsequent PRs so that we can keep the size of each PR reasonable.

feat: add cpr dependency for rest catalog client

---

CMakeLists.txt
src/iceberg/version.h.in

Create compile-time version information from the project version.
I have tested that the added version macros are properly generated and functional.

feat: add version header generation support

---

src/iceberg/CMakeLists.txt
src/iceberg/manifest_reader_internal.cc
src/iceberg/manifest_reader_internal.h
src/iceberg/row/CMakeLists.txt
src/iceberg/row/arrow_array_wrapper.cc
src/iceberg/row/arrow_array_wrapper.h
src/iceberg/row/manifest_wrapper.cc
src/iceberg/row/manifest_wrapper.h
src/iceberg/row/struct_like.h
src/iceberg/test/CMakeLists.txt
src/iceberg/test/struct_like_test.cc
src/iceberg/type_fwd.h

- Add StructLike, MapLike, and ArrayLike interfaces
- Add wrapper for ManifestFile and ArrowArray

feat: add row-based immutable data structure
